apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  azureDisk:
    kind: Managed
    diskName: my-disk
    diskURI: /subscriptions/3d3f9d9d-b827-472a-96e3-0f5ea834be5a/resourceGroups/K8SAKSResourceGroup/providers/Microsoft.Compute/disks/k8s_storage
  mountOptions:
    - hard
    - nfsvers=4.1